### ISSUE TITLE
[Insight] Deprecated class found in service definition

### ISSUE THREAD

**Issue by RobinBilly** [TechGameCrew/GyverProject#1]
> The annotation_reader service uses the Doctrine\Common\Annotations\FileCacheReader class, which has been deprecated in Doctrine Annotations 1.2.3. Use the Doctrine\Common\Annotations\CachedReader class instead.

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/b7ec2306-4268-4661-b2d3-64e667800a25/analyses/27)_

**Comment by RobinBilly** [comment]
### This bug will be fixed in version 2.0.0 of doctrine/annotations.
This issue has been reported on https://github.com/doctrine/annotations/pull/48/files

We are currently using the latest release of doctrine/annotations (1.2.7)
Watch regularly that version 2.0.0 was released on https://github.com/doctrine/annotations/releases

**Comment by Thibaut-gauvin** [comment]
Fixed
